//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridDemo.WinPhone.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GridLocalizationRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GridLocalizationRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GridDemo.WinPhone.Resources.GridLocalizationRes", typeof(GridLocalizationRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (All).
        /// </summary>
        public static string GridStringId_Caption_All {
            get {
                return ResourceManager.GetString("GridStringId.Caption_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Columns.
        /// </summary>
        public static string GridStringId_Caption_ColumnChooser {
            get {
                return ResourceManager.GetString("GridStringId.Caption_ColumnChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string GridStringId_Caption_Off {
            get {
                return ResourceManager.GetString("GridStringId.Caption_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ON .
        /// </summary>
        public static string GridStringId_Caption_On {
            get {
                return ResourceManager.GetString("GridStringId.Caption_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   0  .
        /// </summary>
        public static string GridStringId_Caption_Undefined {
            get {
                return ResourceManager.GetString("GridStringId.Caption_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GridStringId_ColumnChooserDlg_ButtonCancel {
            get {
                return ResourceManager.GetString("GridStringId.ColumnChooserDlg_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string GridStringId_ColumnChooserDlg_ButtonOk {
            get {
                return ResourceManager.GetString("GridStringId.ColumnChooserDlg_ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Columns.
        /// </summary>
        public static string GridStringId_ColumnChooserDlg_LabelCaption {
            get {
                return ResourceManager.GetString("GridStringId.ColumnChooserDlg_LabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg.
        /// </summary>
        public static string GridStringId_FilterExpression_Aggregate_Avg {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Aggregate_Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string GridStringId_FilterExpression_Aggregate_Count {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Aggregate_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists.
        /// </summary>
        public static string GridStringId_FilterExpression_Aggregate_Exists {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Aggregate_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string GridStringId_FilterExpression_Aggregate_Max {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Aggregate_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string GridStringId_FilterExpression_Aggregate_Min {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Aggregate_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string GridStringId_FilterExpression_Aggregate_Single {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Aggregate_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string GridStringId_FilterExpression_Aggregate_Sum {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Aggregate_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between.
        /// </summary>
        public static string GridStringId_FilterExpression_Between {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;.
        /// </summary>
        public static string GridStringId_FilterExpression_BinaryOperator_BitwiseAnd {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_BinaryOperator_BitwiseAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        public static string GridStringId_FilterExpression_BinaryOperator_BitwiseOr {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_BinaryOperator_BitwiseOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^.
        /// </summary>
        public static string GridStringId_FilterExpression_BinaryOperator_BitwiseXor {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_BinaryOperator_BitwiseXor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string GridStringId_FilterExpression_BinaryOperator_Divide {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_BinaryOperator_Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        public static string GridStringId_FilterExpression_BinaryOperator_Equal {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_BinaryOperator_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string GridStringId_FilterExpression_BinaryOperator_Greater {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_BinaryOperator_Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        public static string GridStringId_FilterExpression_BinaryOperator_GreaterOrEqual {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_BinaryOperator_GreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string GridStringId_FilterExpression_BinaryOperator_Less {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_BinaryOperator_Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        public static string GridStringId_FilterExpression_BinaryOperator_LessOrEqual {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_BinaryOperator_LessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string GridStringId_FilterExpression_BinaryOperator_Like {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_BinaryOperator_Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string GridStringId_FilterExpression_BinaryOperator_Minus {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_BinaryOperator_Minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string GridStringId_FilterExpression_BinaryOperator_Modulo {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_BinaryOperator_Modulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string GridStringId_FilterExpression_BinaryOperator_Multiply {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_BinaryOperator_Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&gt;.
        /// </summary>
        public static string GridStringId_FilterExpression_BinaryOperator_NotEqual {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_BinaryOperator_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string GridStringId_FilterExpression_BinaryOperator_Plus {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_BinaryOperator_Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abs.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Abs {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Abs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acos.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Acos {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Acos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add days.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_AddDays {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_AddDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add hours.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_AddHours {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_AddHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add milliseconds.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_AddMilliSeconds {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_AddMilliSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add minutes.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_AddMinutes {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_AddMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add months.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_AddMonths {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_AddMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add seconds.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_AddSeconds {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_AddSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ticks.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_AddTicks {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_AddTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add time span.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_AddTimeSpan {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_AddTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add years.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_AddYears {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_AddYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascii.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Ascii {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Ascii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asin.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Asin {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Asin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atn.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Atn {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Atn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atn2.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Atn2 {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Atn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big mul.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_BigMul {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_BigMul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceiling.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Ceiling {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Ceiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Char {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char index.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_CharIndex {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_CharIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concat.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Concat {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Concat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Contains {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cos.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Cos {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Cos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosh.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Cosh {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Cosh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Custom {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom non deterministic.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_CustomNonDeterministic {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_CustomNonDeterministic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date diff day.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_DateDiffDay {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_DateDiffDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date diff hour.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_DateDiffHour {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_DateDiffHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date diff millisecond.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_DateDiffMilliSecond {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_DateDiffMilliSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date diff minute.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_DateDiffMinute {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_DateDiffMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date diff month.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_DateDiffMonth {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_DateDiffMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date diff second.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_DateDiffSecond {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_DateDiffSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date diff tick.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_DateDiffTick {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_DateDiffTick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date diff year.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_DateDiffYear {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_DateDiffYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_EndsWith {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Exp {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Floor {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get date.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_GetDate {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_GetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get day.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_GetDay {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_GetDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get day of week.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_GetDayOfWeek {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_GetDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get day of year.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_GetDayOfYear {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_GetDayOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get hour.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_GetHour {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_GetHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get millisecond.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_GetMilliSecond {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_GetMilliSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get minute.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_GetMinute {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_GetMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get month.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_GetMonth {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_GetMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get second.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_GetSecond {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_GetSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get time of day.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_GetTimeOfDay {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_GetTimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get year.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_GetYear {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_GetYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iif.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Iif {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Iif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Insert {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsNull.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_IsNull {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null or empty.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_IsNullOrEmpty {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is beyond this year.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_IsOutlookIntervalBeyondThisYear {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_IsOutlookIntervalBeyondThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is earlier this month.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_IsOutlookIntervalEarlierThisMonth {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_IsOutlookIntervalEarlierThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is earlier this week.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_IsOutlookIntervalEarlierThisWeek {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_IsOutlookIntervalEarlierThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is earlier this year.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_IsOutlookIntervalEarlierThisYear {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_IsOutlookIntervalEarlierThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is last week.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_IsOutlookIntervalLastWeek {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_IsOutlookIntervalLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is later this month.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_IsOutlookIntervalLaterThisMonth {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_IsOutlookIntervalLaterThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is later this week.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_IsOutlookIntervalLaterThisWeek {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_IsOutlookIntervalLaterThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is later this year.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_IsOutlookIntervalLaterThisYear {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_IsOutlookIntervalLaterThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is next week.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_IsOutlookIntervalNextWeek {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_IsOutlookIntervalNextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is prior to this year.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_IsOutlookIntervalPriorThisYear {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_IsOutlookIntervalPriorThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is today.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_IsOutlookIntervalToday {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_IsOutlookIntervalToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is tomorrow.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_IsOutlookIntervalTomorrow {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_IsOutlookIntervalTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is yesterday.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_IsOutlookIntervalYesterday {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_IsOutlookIntervalYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Len.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Len {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day after tomorrow.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_LocalDateTimeDayAfterTomorrow {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_LocalDateTimeDayAfterTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_LocalDateTimeLastWeek {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_LocalDateTimeLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next month.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_LocalDateTimeNextMonth {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_LocalDateTimeNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next week.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_LocalDateTimeNextWeek {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_LocalDateTimeNextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next year.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_LocalDateTimeNextYear {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_LocalDateTimeNextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_LocalDateTimeNow {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_LocalDateTimeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_LocalDateTimeThisMonth {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_LocalDateTimeThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_LocalDateTimeThisWeek {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_LocalDateTimeThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This year.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_LocalDateTimeThisYear {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_LocalDateTimeThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_LocalDateTimeToday {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_LocalDateTimeToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_LocalDateTimeTomorrow {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_LocalDateTimeTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two weeks away.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_LocalDateTimeTwoWeeksAway {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_LocalDateTimeTwoWeeksAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_LocalDateTimeYesterday {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_LocalDateTimeYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Log {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log10.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Log10 {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Log10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Lower {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Max {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Min {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_None {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Now {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad left.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_PadLeft {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_PadLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad right.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_PadRight {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_PadRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Power {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Remove {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Replace {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Reverse {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rnd.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Rnd {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Rnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Round {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Sign {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Sin {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Sin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinh.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Sinh {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Sinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sqr.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Sqr {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Sqr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_StartsWith {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substring.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Substring {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Substring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Tan {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanh.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Tanh {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Tanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Today {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To decimal.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_ToDecimal {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_ToDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To double.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_ToDouble {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_ToDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To float.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_ToFloat {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_ToFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To int.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_ToInt {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_ToInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To long.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_ToLong {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_ToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To str.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_ToStr {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_ToStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Trim {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Trim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_Upper {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utc now.
        /// </summary>
        public static string GridStringId_FilterExpression_Function_UtcNow {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_Function_UtcNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string GridStringId_FilterExpression_GroupOperator_And {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_GroupOperator_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string GridStringId_FilterExpression_GroupOperator_Or {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_GroupOperator_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string GridStringId_FilterExpression_In {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Not Null.
        /// </summary>
        public static string GridStringId_FilterExpression_IsNotNull {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Null.
        /// </summary>
        public static string GridStringId_FilterExpression_IsNull {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Like.
        /// </summary>
        public static string GridStringId_FilterExpression_NotLike {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_NotLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~.
        /// </summary>
        public static string GridStringId_FilterExpression_UnaryOperator_BitwiseNot {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_UnaryOperator_BitwiseNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Null.
        /// </summary>
        public static string GridStringId_FilterExpression_UnaryOperator_IsNull {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_UnaryOperator_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string GridStringId_FilterExpression_UnaryOperator_Minus {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_UnaryOperator_Minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        public static string GridStringId_FilterExpression_UnaryOperator_Not {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_UnaryOperator_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string GridStringId_FilterExpression_UnaryOperator_Plus {
            get {
                return ResourceManager.GetString("GridStringId.FilterExpression_UnaryOperator_Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older;Last Month;Earlier this Month;Three Weeks Ago;Two Weeks Ago;Last Week;;;;;;;;Yesterday;Today;Tomorrow;;;;;;;;Next Week;Two Weeks Away;Three Weeks Away;Later this Month;Next Month;Beyond Next Month;.
        /// </summary>
        public static string GridStringId_GridOutlookIntervals {
            get {
                return ResourceManager.GetString("GridStringId.GridOutlookIntervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string GridStringId_GroupCaptionDisplayFormat {
            get {
                return ResourceManager.GetString("GridStringId.GroupCaptionDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        public static string GridStringId_GroupIntervalMonthDisplayFormat {
            get {
                return ResourceManager.GetString("GridStringId.GroupIntervalMonthDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q{0}, {1}.
        /// </summary>
        public static string GridStringId_GroupIntervalQuarterDisplayFormat {
            get {
                return ResourceManager.GetString("GridStringId.GroupIntervalQuarterDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string GridStringId_GroupIntervalYearDisplayFormat {
            get {
                return ResourceManager.GetString("GridStringId.GroupIntervalYearDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (null).
        /// </summary>
        public static string GridStringId_GroupNameNull {
            get {
                return ResourceManager.GetString("GridStringId.GroupNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} is {2}.
        /// </summary>
        public static string GridStringId_GroupSummaryDisplayFormat {
            get {
                return ResourceManager.GetString("GridStringId.GroupSummaryDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By &apos;{0}&apos;.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnGroup {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By &apos;{0}&apos;..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnGroupDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Grouping.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnGroupNone {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnGroupNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Grouping..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnGroupNoneDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnGroupNoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnGroupSummaryAverage {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnGroupSummaryAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnGroupSummaryAverageDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnGroupSummaryAverageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnGroupSummaryCount {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnGroupSummaryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnGroupSummaryCountDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnGroupSummaryCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnGroupSummaryMax {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnGroupSummaryMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnGroupSummaryMaxDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnGroupSummaryMaxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnGroupSummaryMin {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnGroupSummaryMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnGroupSummaryMinDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnGroupSummaryMinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnGroupSummaryNone {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnGroupSummaryNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnGroupSummaryNoneDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnGroupSummaryNoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnGroupSummarySum {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnGroupSummarySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnGroupSummarySumDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnGroupSummarySumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Ascending.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnSortAscending {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnSortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Ascending..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnSortAscendingDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnSortAscendingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Descending.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnSortDescending {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnSortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Descending..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnSortDescendingDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnSortDescendingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sort.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnSortNone {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnSortNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sort..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnSortNoneDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnSortNoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnTotalSummaryAverage {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnTotalSummaryAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnTotalSummaryAverageDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnTotalSummaryAverageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnTotalSummaryCount {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnTotalSummaryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnTotalSummaryCountDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnTotalSummaryCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnTotalSummaryMax {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnTotalSummaryMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnTotalSummaryMaxDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnTotalSummaryMaxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnTotalSummaryMin {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnTotalSummaryMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnTotalSummaryMinDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnTotalSummaryMinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnTotalSummaryNone {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnTotalSummaryNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnTotalSummaryNoneDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnTotalSummaryNoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnTotalSummarySum {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnTotalSummarySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum..
        /// </summary>
        public static string GridStringId_MenuCmd_ColumnTotalSummarySumDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ColumnTotalSummarySumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row.
        /// </summary>
        public static string GridStringId_MenuCmd_DataRowDelete {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_DataRowDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row..
        /// </summary>
        public static string GridStringId_MenuCmd_DataRowDeleteDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_DataRowDeleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Cell.
        /// </summary>
        public static string GridStringId_MenuCmd_DataRowEdit {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_DataRowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Cell..
        /// </summary>
        public static string GridStringId_MenuCmd_DataRowEditDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_DataRowEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All Groups.
        /// </summary>
        public static string GridStringId_MenuCmd_GroupsCollapseAll {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_GroupsCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All Groups..
        /// </summary>
        public static string GridStringId_MenuCmd_GroupsCollapseAllDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_GroupsCollapseAllDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All Groups.
        /// </summary>
        public static string GridStringId_MenuCmd_GroupsExpandAll {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_GroupsExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All Groups..
        /// </summary>
        public static string GridStringId_MenuCmd_GroupsExpandAllDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_GroupsExpandAllDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string GridStringId_MenuCmd_None {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Column Chooser.
        /// </summary>
        public static string GridStringId_MenuCmd_ShowColumnChooser {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ShowColumnChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Column Chooser..
        /// </summary>
        public static string GridStringId_MenuCmd_ShowColumnChooserDescription {
            get {
                return ResourceManager.GetString("GridStringId.MenuCmd_ShowColumnChooserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error is occured!.
        /// </summary>
        public static string GridStringId_Msg_ErrorInternalError {
            get {
                return ResourceManager.GetString("GridStringId.Msg_ErrorInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap here to add a new row.
        /// </summary>
        public static string GridStringId_NewItemRowCaption {
            get {
                return ResourceManager.GetString("GridStringId.NewItemRowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {2}.
        /// </summary>
        public static string GridStringId_TotalSummaryDisplayFormat {
            get {
                return ResourceManager.GetString("GridStringId.TotalSummaryDisplayFormat", resourceCulture);
            }
        }
    }
}
