// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("StockAnalyzer.CS")]
[assembly: AssemblyProductAttribute("FunctionalConcurrencyNET")]
[assembly: AssemblyDescriptionAttribute("Source code for the book Functional Concurrency .NET")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
